### PR TITLE
Jruby 9.2.7.0

### LINKED ISSUE #48: Support 9.2.7.0
[Jruby 9.2.7.0 has been released](https://www.jruby.org/2019/04/09/jruby-9-2-7-0.html), so it'd be nice to get the new image built in this repo.

Thanks!!

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Closes #48.

Includes two other related changes. At the beginning I was getting a 404 when running `./update.sh`. I initially thought the s3 urls no longer worked because of https://github.com/rbenv/ruby-build/issues/1148. But in the end the problem was that the scripts used the `$(< VERSION)` construct which doesn't work in my default shell ([`dash`](https://wiki.ubuntu.com/DashAsBinSh)).

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Thanks!
In order for the image to be updated, the manifest in docker-library/official-images needs to also be updated.

I can do this tomorrow, but also feel free to open a pr over there :)

❤️

**Comment by deivid-rodriguez** [comment]
Thanks! If you can do it tomorrow, that's great, otherwise I'll look into creating that PR :+1:

**Comment by deivid-rodriguez** [comment]
Looked into what's need [in the previous bump](https://github.com/docker-library/official-images/pull/5444) and looks easy enough. I'll do it! :+1:

**Comment by deivid-rodriguez** [comment]
Done! https://github.com/docker-library/official-images/pull/5726

**Comment by cpuguy83** [comment]
Thanks!

**Pull request merged**
