### PR TITLE
update to version 1.7.23

### PR DESCRIPTION
**Pull request by jtarchie**
This adds support for JRuby 1.7.23.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM, thanks!

**Comment by jtarchie** [comment]
Thanks, @cpuguy83. I've noticed that some of the _official_ docker repos for some runtimes are out of date. More than happy to help with PRs, but on my project we have a notification (Slack message and Pivotal Tracker story) system that let's us know of new releases of several runtimes (JRuby included). Any interest in something like that?

@flavorjones, since this was accepted, expect a PR on your side soon.

**Comment by cpuguy83** [comment]
@jtarchie For this it was mostly time/prioritization, and it came while I was on vacation.

Did you want to go ahead and make the PR to github.com/docker/docker-library to update the commit/version info?

**Comment by jtarchie** [comment]
This repo (github.com/docker/docker-library) does not exist. What is the next step to getting this deployed?

**Comment by cpuguy83** [comment]
sorry - https://github.com/docker-library/official-images

**Comment by jtarchie** [comment]
@cpuguy83 going to be honest. Read the README.md and still don't understand what pull request needs to be made.

**Comment by cpuguy83** [comment]
See docker-library/official-images#1344

Basically, we have to update that repo under `library/jruby` with the commit sha from this PR, and update the version numbers (remove .22->.23)

**Comment by jtarchie** [comment]
Sounds like this needs to be _automated_.

automate all the things

I'll get on this.

**Pull request merged**
