### PR TITLE
JRuby 9.2.13.0

### PR DESCRIPTION
**Pull request by reidmorrison**

### CODE REVIEW

**Comment by jsmestad** [comment]
Yes please!

**Review by cpuguy83 — APPROVED** [review]
LGTM

Sorry for the delay. I missed this PR while I was on PTO.

**Comment by reidmorrison** [comment]
Thank you for merging the PR. 
Is there anything I can do to update the references on Docker hub so that it builds the latest version?

**Comment by cpuguy83** [comment]
@reidmorrison The references in https://github.com/docker-library/official-images need to be updated.
Would you like to handle that?

**Comment by reidmorrison** [comment]
Ah, yes I can do that. Found the previous JRuby upgrade PR that I will use as an example.

**Pull request merged**
