### PR TITLE
Introduce JRE 17 images

### LINKED ISSUE #83: JRuby with JRE 17
Hello,

Is there a particular reason why there's no jruby:9.4 with JRE 17?

If not, I'll be happy to provide a PR.

### PR DESCRIPTION
**Pull request by nfrankel**

### CODE REVIEW

**Comment by headius** [comment]
I'm swamped getting ready for a conf; could you add a CI runs for JRE 17 too?

**Review by headius — APPROVED** [review]

**Comment by nfrankel** [comment]
I've added the two images in the matrix

**Comment by headius** [comment]
Looks good, thanks!

**Comment by nfrankel** [comment]
Thanks for your quick feedback!

**Comment by headius** [comment]
It has been merged by docker hub and should be live now!

**Comment by nfrankel** [comment]
Thank you! A question if I may: what's your policy regarding JDK/JRE versions? 21 is considered LTS by Oracle and others, do you intend to offer it?

**Comment by headius** [comment]
We will include all Oracle LTS levels that are still active, as far back as the base supported version (8 for 9.4, 11 or 17 for 9.5).

**Comment by nfrankel** [comment]
Thanks for your quick feedback!

**Pull request merged**
